# Generated by Django 4.0.3 on 2022-03-27 16:39

import datetime
from django.db import migrations, models, connection
from django.utils.timezone import utc

from plan.models import Schedule

def find_repeated_schedules_and_remove(apps, schema_editor):
    with connection.cursor() as cursor:
        cursor.execute('''
        select s1.id
        from plan_schedule as s1
        inner join plan_schedule as s2
            on s1.room_id = s2.room_id
            and s1.date_time = s2.date_time
            and s1.id > s2.id;
        ''')
        ids = cursor.fetchall()
    ids = list(map(lambda i: i[0], ids))
    schedules = Schedule.objects.filter(id__in=ids)
    schedules.delete()
    


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_ticket_seat'),
    ]

    operations = [
        migrations.RunPython(find_repeated_schedules_and_remove, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=127, unique=True, verbose_name='name'),
        ),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.UniqueConstraint(fields=('title', 'poster'), name='unique_title'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('room', 'date_time'), name='unique_room_datetime'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'row', 'column'), name='unique_room_row_column'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('room', 'seat_id'), name='unique_room_seat_id'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('schedule', 'seat'), name='unique_ticket'),
        ),
    ]
